force-app/main/default/objects/DFDFW_Service__mdt/DFDFW_Service__mdt.object-meta.xml
<CustomObject>
    <label>DFDFW Service</label>
    <pluralLabel>DFDFW Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Active__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Address_Validation__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Address_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Document_Upload__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Document_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Icon_File_Name__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Icon_File_Name__c</fullName>
    <label>Icon File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Notice_Text__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Notice_Text__c</fullName>
    <label>Notice Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Service_URL__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Service_URL__c</fullName>
    <label>Service URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Tile_Subheading__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Tile_Subheading__c</fullName>
    <label>Tile Subheading</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DFDFW_Service__mdt/fields/DFDFW_Tile_Title__c.field-meta.xml
<CustomField>
    <fullName>DFDFW_Tile_Title__c</fullName>
    <label>Tile Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DFDFW_TILECONFIG_ServicesController.cls
/*
*********************************************************
Apex Class Name    : DFDFW_TILECONFIG_ServicesController
Created Date       : 7/3/2024
Author             : Cloud Synapps Inc.
Description        : Class used as controller for getting details related to services.
Test Class Name    : DFDFW_TILECONFIG_ServicesControllerTest
*********************************************************
*/
public with sharing class DFDFW_TILECONFIG_ServicesController {
  /*
  *********************************************************
  @method Name    : getEventTiles
  @description    : used to get metadata for services.
  @param          : serviceType
  @return         : List<DFDFW_Service__mdt>
  ********************************************************
  */
  @AuraEnabled(cacheable=true)
  public static List<DFDFW_Service__mdt> getEventTiles(String serviceType) {
    try {
      List<DFDFW_Service__mdt> eventList = new List<DFDFW_Service__mdt>();
        eventList =[SELECT Id, DFDFW_Tile_Title__c, DFDFW_Active__c, DFDFW_Icon_File_Name__c, DFDFW_Notice_Text__c,
          			DFDFW_Service_URL__c, DFDFW_Tile_Subheading__c, DFDFW_Address_Validation__c,
          				DFDFW_Document_Upload__c FROM DFDFW_Service__mdt
                    	WHERE DFDFW_Active__c = TRUE];
      return eventList;
    } catch (Exception e) {new DFDFW_LOG_AllException().Module('Services Controller').Log(e); throw new AuraHandledException(e.getMessage() + '===>' + e.getLineNumber());}
  }

  /*
  *********************************************************
  @method Name    : getNoticeDetails
  @description    : used to get notice details from metadata.
  @param          : 
  @return         : List<DFDFW_Service__mdt>
  ********************************************************
  */
  @AuraEnabled(cacheable=true)
  public static List<DFDFW_Service__mdt> getNoticeDetails() {
    try {
      List<DFDFW_Service__mdt> noticeEventList = new List<DFDFW_Service__mdt>();
        noticeEventList = [SELECT Id, DFDFW_Tile_Title__c, DFDFW_Active__c, DFDFW_Notice_Text__c,
          					DFDFW_Tile_Subheading__c FROM DFDFW_Service__mdt
        					WHERE DFDFW_Active__c = TRUE];
      return noticeEventList;
    } catch (Exception e) {new DFDFW_LOG_AllException().Module('Services Controller').Log(e); throw new AuraHandledException(e.getMessage() + '===>' + e.getLineNumber());}
  }

  /*
  *********************************************************
  @method Name    : getServiceDetails
  @description    : used to get event informations
  @param          : evenType
  @return         : String
  ********************************************************
  */
  /*@AuraEnabled
  public static String getServiceDetails(String eventType) {
    try {
      DFDFW_Service__mdt ge = [SELECT EventPermitEndpoint__c, DFDFW_Address_Validation__c, DFDFW_Tile_Title__c
        					FROM DFDFW_Service__mdt WHERE DFDFW_Tile_Title__c = :eventType LIMIT 1];
      String endpoint = ge.EventPermitEndpoint__c;
      String jsonBody = DFDFW_INTGEN_CallOutController.callout( endpoint,'GET', false, null, false, null);
      return jsonBody;
    } 
      catch (Exception e) {new DFDFW_LOG_AllException().Module('Services controller').Log(e);throw new AuraHandledException(e.getMessage());}
  }*/
}