force-app/main/default/objects/DFD_OIC_Template_Id__mdt/DFD_OIC_Template_Id__mdt.object-meta.xml
<CustomObject>
    <label>DFD OIC Template Id</label>
    <pluralLabel>DFD OIC Template Ids</pluralLabel>
</CustomObject>

force-app/main/default/objects/DFD_OIC_Template_Id__mdt/fields/Permit_Id__c.field-meta.xml
<CustomField>
    <fullName>Permit_Id__c</fullName>
    <label>Permit Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFD_OIC_Template_Id__mdt/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <label>Template Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DFD_Service_Configuration__c/DFD_Service_Configuration__c.object-meta.xml
<CustomObject>
    <label>Service Configuration</label>
    <nameField>
        <label>Business Rule Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Configurations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DFD_Service_Rule__c/DFD_Service_Rule__c.object-meta.xml
<CustomObject>
    <label>Service Rule</label>
    <nameField>
        <label>Service Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DFD_Service_Rule__c/fields/Payload_Details_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Payload_Details_Mapping__c</fullName>
    <label>Payload Details Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DFD_Service_Rule__c/fields/Service_Rule_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Service_Rule_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Rule Configuration</label>
    <referenceTo>DFD_Service_Configuration__c</referenceTo>
    <relationshipLabel>Service Rules</relationshipLabel>
    <relationshipName>Service_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFDFW_INTOIC_DataMapper.cls
/*
*********************************************************
Apex Class Name    : DFDFW_INTOIC_DataMapper
Created Date       : 9/18/2024
Author             : Cloud Synapps Inc.
Description        : Class used to create mapping for payload to be sent on OIC for permit creation
Test Class Name    : DFDFW_INTOIC_DataMapperTest
*********************************************************
*/
public class DFDFW_INTOIC_DataMapper {
  /*
  *********************************************************
  @method Name    : parseJson
  @description    : used to get table configurations
  @param          : applicationJsonString
  @param          : businessRuleName
  @return         : String
  ********************************************************
  */
  public static String parseJson(
    String applicationJsonString,
    String businessRuleName
  ) {
    try {
      Map<String, Object> applicationJSON = (Map<String, Object>) JSON.deserializeuntyped(
        applicationJsonString
      );
      List<DFD_Service_Rule__c> brList = [
        SELECT Id, Name, Payload_Details_Mapping__c
        FROM DFD_Service_Rule__c
        WHERE
          Service_Rule_Configuration__r.Name = :businessRuleName
          AND Service_Rule_Configuration__r.Active__c = TRUE
          AND Active__c = TRUE
      ];
      Map<String, DFD_Service_Rule__c> brNameTosObj = new Map<String, DFD_Service_Rule__c>();
      Map<String, Object> payloadMap = new Map<String, Object>();
      if (!brList.isEmpty()) {
        for (DFD_Service_Rule__c br : brList) {
          brNameTosObj.put(br.Name, br);
        }
        if (brNameTosObj != null) {
          if (brNameTosObj.containsKey('JSON Map')) {
            Map<String, Object> payloadJsonMapping = (Map<String, Object>) JSON.deserializeuntyped(
              brNameTosObj.get('JSON Map').Payload_Details_Mapping__c
            );
            List<Object> mappedData = new List<Object>();
            if (payloadJsonMapping != null) {
              for (String key : applicationJSON.keySet()) {
                Map<String, Object> objmap = new Map<String, Object>();
                Map<String, Object> brKey = (Map<String, Object>) payloadJsonMapping.get(
                  key
                );
                if (brKey != null) {
                  objMap.put('DetailCode', brKey.get('DetailCode'));
                    if(brKey.containsKey('DefaultValue')) {
                        objMap.put((String)brKey.get('DetailValueType'), (String) brKey.get('DefaultValue'));
                    } else {
                        objMap.put((String) brKey.get('DetailValueType'),applicationJSON.get(key));
                    }
                 
                  mappedData.add(objMap);
                }
              }
            }
            payloadMap.put('Details', mappedData);
          }
          if (brNameTosObj.containsKey('Address Coordinate')) {
            Map<String, Object> payloadJsonMapping = (Map<String, Object>) JSON.deserializeuntyped(
              brNameTosObj.get('Address Coordinate').Payload_Details_Mapping__c
            );
            if (payloadJsonMapping != null) {
              for (String key : payloadJsonMapping.keySet()) {
                String keyVal = (String) payloadJsonMapping.get(key);
                payloadMap.put(key, applicationJson.get(keyVal));
              }
            }
          }
          if (brNameTosObj.containsKey('OIC Keys')) {
            Map<String, Object> metadataMapping = (Map<String, Object>) JSON.deserializeUntyped(
              brNameTosObj.get('OIC Keys').Payload_Details_Mapping__c
            );
            Map<String, Object> payloadJsonMapping_metadata = (Map<String, Object>) metadataMapping.get(
              'mapping_metadata'
            );
            Map<String, Object> payloadJsonMapping_application = (Map<String, Object>) metadataMapping.get(
              'mapping_application'
            );
            List<DFD_OIC_Template_Id__mdt> templateIdMdt = new List<DFD_OIC_Template_Id__mdt>();
            if (metadataMapping != null) {
              String mdtLabel = (String) metadataMapping.get('label');
              templateIdMdt = [
                SELECT Id, Permit_Id__c, Template_Id__c, MasterLabel
                FROM DFD_OIC_Template_Id__mdt
                WHERE MasterLabel = :mdtLabel
                LIMIT 1
              ];
            }
              
              if(payloadJsonMapping_application != null) {
                  for(String key : payloadJsonMapping_application.keySet()) {
                      String keyVal = (String) payloadJsonMapping_application.get(key);
                      payloadMap.put(key, applicationJSON.get(keyVal));
                  }
              }
            if (payloadJsonMapping_metadata != null) {
              for (String key : payloadJsonMapping_metadata.keySet()) {
                String keyVal = (String) payloadJsonMapping_metadata.get(key);
                if (templateIdMdt[0].get(keyVal) != null) {
                  payloadMap.put(key, templateIdMdt[0].get(keyVal));
                } else {
                  payloadMap.put(key, '');
                }
              }
            }
          }
        }
      }

      String payloadJson = JSON.serialize(payloadMap);
      return payloadJson;
    } catch (Exception ex) {
      new DFDFW_LOG_AllException().Module('OIC Payload Mapping').Log(ex);
      return null;
    }
  }
}