force-app/main/default/objects/Service_Application_Detail__c/Service_Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Created this object to capture the details of city permits</description>
    <label>Service Application Detail</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Application Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/fields/Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Special Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created this field to capture the status of the applications</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on customer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sub_Application__c/Sub_Application__c.object-meta.xml
<CustomObject>
    <label>Sub-Application</label>
    <nameField>
        <displayFormat>SAP-{000000}</displayFormat>
        <label>Sub-Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Application__c/fields/Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Streets</fullName>
            </value>
            <value>
                <fullName>Parks</fullName>
            </value>
            <value>
                <fullName>Park Permit</fullName>
                <isActive>false</isActive>
                <label>Park Permit</label>
            </value>
            <value>
                <fullName>Street Permit</fullName>
                <isActive>false</isActive>
                <label>Street Permit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sub_Application__c/fields/Service_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>Service_Application_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Application Detail</label>
    <referenceTo>Service_Application_Detail__c</referenceTo>
    <relationshipLabel>Sub-Applications</relationshipLabel>
    <relationshipName>Sub_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFDFW_APP_GetSubAppControllerTest.cls
/*
*********************************************************
Apex Class Name    : DFDFW_APP_GetSubAppControllerTest
Created Date       : 12/2/2024
Author             : Cloud Synapps Inc.
Description        : Class used as test class for DFDFW_APP_GetSubAppController.
*********************************************************
*/
@isTest
private class DFDFW_APP_GetSubAppControllerTest {
    @isTest
    static void testGetRelatedSubApplications() {

        // Create a test Service Application Detail record
        Service_Application_Detail__c testServiceApplicationDetail = new Service_Application_Detail__c();
        insert testServiceApplicationDetail;

        // Create related Sub_Application__c records
        Sub_Application__c subApp1 = new Sub_Application__c(
            Permit_Type__c = 'Streets',
            Service_Application_Detail__c = testServiceApplicationDetail.Id
        );
        Sub_Application__c subApp2 = new Sub_Application__c(
            Permit_Type__c = 'Parks',
            Service_Application_Detail__c = testServiceApplicationDetail.Id
        );

       
        insert new List<Sub_Application__c>{subApp1, subApp2};
        

        Test.startTest();
        // Call the method and store the result
        List<Sub_Application__c> relatedSubApplications = DFDFW_APP_GetSubAppController.getRelatedSubApplications(testServiceApplicationDetail.Id);
        Test.stopTest();
        // Assertions to verify the results
        Assert.areEqual(2, relatedSubApplications.size(), 'There should be 2 related sub-applications.');

        Sub_Application__c subApp3 = new Sub_Application__c(
            Permit_Type__c = 'Parks',
            Service_Application_Detail__c = testServiceApplicationDetail.Id,
            Status__c = 'Pending'        );
        insert subApp3;

    }
}