force-app/main/default/objects/Account/recordTypes/Organizations.recordType-meta.xml
<RecordType>
    <fullName>Organizations</fullName>
    <active>true</active>
    <label>Organizations</label>
</RecordType>

force-app/main/default/objects/Checklist_Details__c/Checklist_Details__c.object-meta.xml
<CustomObject>
    <label>Checklist Details</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Checklist Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Details__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Checklist Details</relationshipLabel>
    <relationshipName>Checklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/CDAProgramatic.recordType-meta.xml
<RecordType>
    <fullName>CDAProgramatic</fullName>
    <active>true</active>
    <label>CDA Programatic</label>
</RecordType>

force-app/main/default/objects/Reference_Checks__c/Reference_Checks__c.object-meta.xml
<CustomObject>
    <label>Reference Checks</label>
    <nameField>
        <label>Reference Checks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Checks_Details__c/Reference_Checks_Details__c.object-meta.xml
<CustomObject>
    <label>Reference Checks Details</label>
    <nameField>
        <displayFormat>RCD-{0000}</displayFormat>
        <label>Reference Checks Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Checks Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Checks_Details__c/fields/Reference_Checks__c.field-meta.xml
<CustomField>
    <fullName>Reference_Checks__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Checks</label>
    <referenceTo>Reference_Checks__c</referenceTo>
    <relationshipLabel>Reference Checks Details</relationshipLabel>
    <relationshipName>Reference_Checks_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateNewRecordsFromRecordListTest.cls
@IsTest
public with sharing class CreateNewRecordsFromRecordListTest {

    @TestSetup
    static void makeData() {
        Reference_Checks__c refCheck = new Reference_Checks__c();
        refCheck.Name = 'Test Reference Checks';
        insert refCheck;

        Reference_Checks_Details__c refCheckDetail = new Reference_Checks_Details__c();
        refCheckDetail.Reference_Checks__c = refCheck.Id;
        refCheckDetail.Display_Name__c = 'Test Reference Checks Detail';
        refCheckDetail.Sort_Order__c = 1;
        insert refCheckDetail;

        Reference_Checks_Details__c refCheckDetail2 = new Reference_Checks_Details__c();
        refCheckDetail2.Reference_Checks__c = refCheck.Id;
        refCheckDetail2.Display_Name__c = 'Test Reference Checks Detail 2';
        refCheckDetail2.Sort_Order__c = 2;
        insert refCheckDetail2;

        Account acct = new Account();
        acct.Name = 'Test Account';
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Organizations').getRecordTypeId();
        insert acct;

        Contract contract = new Contract();
        contract.AccountId = acct.Id;
        contract.Status = 'Draft';
        contract.RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('CDAProgramatic').getRecordTypeId();
        insert contract;

        Checklist_Details__c checklistDetail = new Checklist_Details__c();
        checklistDetail.Contract__c = contract.Id;
        checklistDetail.Display_Name__c = 'Test Reference Checks Detail';
        checklistDetail.Sort_Order__c = 1;
        insert checklistDetail;
    }

    @isTest
    private static void createRecordsTest() {
        Reference_Checks__c refCheck = [SELECT Id FROM Reference_Checks__c LIMIT 1];
        Contract contract = [SELECT Id FROM Contract LIMIT 1];

        List<CreateNewRecordsFromRecordList.Request> requests = new List<CreateNewRecordsFromRecordList.Request>();
        CreateNewRecordsFromRecordList.Request request = new CreateNewRecordsFromRecordList.Request();
        request.sourceObjectApiName = 'Reference_Checks_Details__c';
        request.sourceObjectFilterString = 'Reference_Checks__c = \'' + refCheck.Id + '\'';
        request.sourceDupMatchFieldApiName = 'Display_Name__c';
        request.targetDupMatchFieldApiName = 'Display_Name__c';
        request.targetObjectApiName = 'Checklist_Details__c';
        request.jsonFieldMappings = '{"Display_Name__c":"Display_Name__c","Sort_Order__c":"Sort_Order__c"}';
        request.parentRecordId = contract.Id;
        request.parentLookupFieldApiName = 'Contract__c';
        requests.add(request);

        List<CreateNewRecordsFromRecordList.Result> results = CreateNewRecordsFromRecordList.createNewRecords(requests);
        
        System.assertEquals(results[0].success, true);
    }

    @isTest
    private static void failCreateRecordsTest() {
        List<CreateNewRecordsFromRecordList.Request> requests = new List<CreateNewRecordsFromRecordList.Request>();
        CreateNewRecordsFromRecordList.Request request = new CreateNewRecordsFromRecordList.Request();
        requests.add(request);

        List<CreateNewRecordsFromRecordList.Result> results = CreateNewRecordsFromRecordList.createNewRecords(requests);
        
        System.assertEquals(results[0].success, false);
    }
}