force-app/main/default/objects/DFD_User_Details__c/DFD_User_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DFD User Details</label>
</CustomObject>

force-app/main/default/objects/DFD_User_Details__c/fields/isRegistered__c.field-meta.xml
<CustomField>
    <fullName>isRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRegistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DFD_User_Details__c/fields/Token_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Token_Part_1__c</fullName>
    <label>Token_Part_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Logger__c/Exception_Logger__c.object-meta.xml
<CustomObject>
    <description>Object used to capture exceptions and API callout failures.</description>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/Service_Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Created this object to capture the details of city permits</description>
    <label>Service Application Detail</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Application Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/fields/Case_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Application_Id__c</fullName>
    <description>This field is used as external ID to store the Case Application ID pulled from CityWorks via OIC.</description>
    <externalId>true</externalId>
    <label>Case Application Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/OIC_Status__c.field-meta.xml
<CustomField>
    <fullName>OIC_Status__c</fullName>
    <label>OIC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>FILE</fullName>
            </value>
            <value>
                <fullName>HEARING</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>OPEN</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>RESUBMIT</fullName>
            </value>
            <value>
                <fullName>REVIEW</fullName>
            </value>
            <value>
                <fullName>WITHDRAWN</fullName>
            </value>
            <value>
                <fullName>ISSUED</fullName>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>DRAFT</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Waiting on customer</fullName>
                <isActive>false</isActive>
                <label>Waiting on customer</label>
            </value>
            <value>
                <fullName>YYY</fullName>
                <isActive>false</isActive>
                <label>YYY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Special Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created this field to capture the status of the applications</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on customer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/recordTypes/DFDFW_Permits.recordType-meta.xml
<RecordType>
    <fullName>DFDFW_Permits</fullName>
    <active>true</active>
    <label>Permits</label>
</RecordType>

force-app/main/default/objects/Sub_Application__c/Sub_Application__c.object-meta.xml
<CustomObject>
    <label>Sub-Application</label>
    <nameField>
        <displayFormat>SAP-{000000}</displayFormat>
        <label>Sub-Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Application__c/fields/Case_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Application_Id__c</fullName>
    <description>This field is used as external ID to store the Case Application ID pulled from CityWorks via OIC.</description>
    <externalId>true</externalId>
    <label>Case Application Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sub_Application__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_Application__c/fields/Permit_Type__c.field-meta.xml
<CustomField>
    <fullName>Permit_Type__c</fullName>
    <label>Permit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Streets</fullName>
            </value>
            <value>
                <fullName>Parks</fullName>
            </value>
            <value>
                <fullName>Park Permit</fullName>
                <isActive>false</isActive>
                <label>Park Permit</label>
            </value>
            <value>
                <fullName>Street Permit</fullName>
                <isActive>false</isActive>
                <label>Street Permit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sub_Application__c/fields/Service_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>Service_Application_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Application Detail</label>
    <referenceTo>Service_Application_Detail__c</referenceTo>
    <relationshipLabel>Sub-Applications</relationshipLabel>
    <relationshipName>Sub_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFDFW_INTOIC_GetAppTaskControllerTest.cls
/*
*********************************************************
Apex Class Name    : DFDFW_INTOIC_GetAppTaskControllerTest
Created Date       : 11/21/2024
Author             : Cloud Synapps Inc.
Description        : Class used as test class for DFDFW_INTOIC_GetAppTaskController.
*********************************************************
*/
@IsTest
private class DFDFW_INTOIC_GetAppTaskControllerTest {

    @TestSetup
    static void setupTestData() {

        //Create User Detail record
        String userId = UserInfo.getUserId();
        DFD_User_Details__c ud = new DFD_User_Details__c();
        ud.SetupOwnerId = userId;
        ud.isRegistered__c = true;
        ud.Token_Part_1__c = 'daw3adaw3adaw';
        insert ud;

        Id rt = Schema.SObjectType.Service_Application_Detail__c.getRecordTypeInfosByDeveloperName().get('DFDFW_Permits').getRecordTypeId();

        // Create a test Service_Application_Detail__c record
        Service_Application_Detail__c sad = new Service_Application_Detail__c(
            Case_Application_Id__c = 123456,
            OIC_Status__c = 'OPEN',
            Email__c = 'testingemail@testemailteststlouis.com',
            RecordtypeId = rt
        );
        insert sad;
    }

    @IsTest
    static void testGetColumns() {
        Test.startTest();
        List<Map<String, String>> columns = DFDFW_INTOIC_GetAppTaskController.getColumns('Display_Application_Tasks');
        Test.stopTest();

        Assert.isNotNull(columns, 'Columns should not return null');
    }

    @IsTest
    static void testGetTasksWithMockCallout() {
        // Setup mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(200, '{"Case":[{"CaObjectId":123456,"CaseStatus":"OPEN"}],"Tasks":[{"Name":"Task 1","TaskDesc":"OPEN","ResultDisplay":"IN REVIEW"}],"LinkedPermits":[{"SourceSid":123456,"DestSid":97066}],"Fees":[{"Amount":150,"CaFeeId":323977,"CaObjectId":123456}]}'));

        // Query a test record
        Service_Application_Detail__c sad = [SELECT Id, OIC_Status__c FROM Service_Application_Detail__c LIMIT 1];

        Test.startTest();
        List<Object> tasks = (List<Object>) DFDFW_INTOIC_GetAppTaskController.getTasks(sad.Id).get('Tasks');
        Test.stopTest();

     //   Assert.isNotNull(tasks, 'Tasks should not be null');
     //   Assert.areEqual(1, tasks.size(), 'One task should be available');
    }

    @IsTest
    static void testGetErrorMessage() {
        Test.startTest();
        String errorMessage = DFDFW_INTOIC_GetAppTaskController.getErrorMessage();
        Test.stopTest();

        Assert.isNotNull(errorMessage, 'errorMessage should have a return value');
    }

    @IsTest
    static void testGetPDFDocument() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(200, '[{"CA_REL_DOC_ID": "1235", "DOC_NAME": "Test_Document_1.pdf"}]'));

        // Query a test record
        Service_Application_Detail__c sad = [SELECT Id, Case_Application_Id__c FROM Service_Application_Detail__c LIMIT 1];

        Test.startTest();
        DFDFW_INTOIC_GetAppTaskController.getPDFDocument(sad.Id, (Integer)sad.Case_Application_Id__c);
        Test.stopTest();

        List<ContentVersion> versions = [SELECT Id FROM ContentVersion WHERE FirstPublishLocationId = :sad.Id];
        Assert.areEqual(1, versions.size(), 'A ContentVersion should have been created.');
    }

    @IsTest
    static void testDocumentDownloadApiError() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(500, '{"Error"}'));

        // Query a test record
        Service_Application_Detail__c sad = [SELECT Id, Case_Application_Id__c FROM Service_Application_Detail__c LIMIT 1];

        Test.startTest();
        ContentVersion cv = DFDFW_INTOIC_GetAppTaskController.documentDownload(sad.Id, (Integer)sad.Case_Application_Id__c, 12345, 'TestFile.pdf');
        Test.stopTest();

        Exception_Logger__c el = [SELECT Id FROM Exception_Logger__c LIMIT 1];
        Assert.isNotNull(el, 'One Exception Log should have been created');
    }

    @IsTest
    static void testGetTasksFailAPICallout() {
        // Setup mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(500, '{"Error":"Error reaching endpoint"}'));

        // Query a test record
        Service_Application_Detail__c sad = [SELECT Id, OIC_Status__c FROM Service_Application_Detail__c LIMIT 1];
        
        Test.startTest();
        try{
            List<Object> tasks = (List<Object>) DFDFW_INTOIC_GetAppTaskController.getTasks(sad.Id).get('Tasks');
        }
        catch(Exception e){}
        Test.stopTest();

        Exception_Logger__c el = [SELECT Id FROM Exception_Logger__c LIMIT 1];
        Assert.isNotNull(el, 'One Exception Log should have been created');
    }

    @isTest
    static void testGetSubApplication(){

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(200, '{"Case":[{"CaObjectId":97066, "CaseStatus":"Issued", "CaseType": "STREETS", "CaseNumber": "ST-0023"}]}'));

        // Create test data for Sub_Application__c
        Integer applicationId = 97066; // Application ID to match in the case response

        Service_Application_Detail__c sad = [SELECT Id FROM Service_Application_Detail__c LIMIT 1];
        String serviceAppId = sad.Id;

        // Insert a Sub_Application__c record for testing
        Sub_Application__c existingSubApp = new Sub_Application__c(
            Case_Application_Id__c = applicationId,
            Status__c = 'Draft' // Set initial status as Draft
        );
        insert existingSubApp;

        Test.startTest();
        DFDFW_INTOIC_GetAppTaskController.getSubApplication(applicationId, serviceAppId);
        Test.stopTest();
        
        // Verify the behavior - make assertions about the created Sub_Application__c record
        List<Sub_Application__c> subApps = [SELECT Id, Permit_Type__c, Case_Number__c, Status__c, Service_Application_Detail__c 
                                            FROM Sub_Application__c WHERE Case_Application_Id__c = :applicationId];

        Assert.areEqual(1, subApps.size(), 'Sub Application record should be upserted');
     //   Assert.areEqual('Streets', subApps[0].Permit_Type__c);

    }


    // Mock HTTP response class
    private class MockHttpResponse implements HttpCalloutMock {
        private Integer statusCode;
        private String body;

        public MockHttpResponse(Integer statusCode, String body) {
            this.statusCode = statusCode;
            this.body = body;
        }

        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            
            if(req.getEndpoint().contains('download/case')){
                res.setStatusCode(statusCode);
                res.setBodyAsBlob(Blob.valueOf('Test File Content'));
            }
            else{
                res.setStatusCode(statusCode);
                res.setBody(body);
            }
            
            return res;
        }
    }
}