force-app/main/default/objects/DFD_CityWorks_Endpoint__mdt/DFD_CityWorks_Endpoint__mdt.object-meta.xml
<CustomObject>
    <label>DFD CityWorks Endpoint</label>
    <pluralLabel>DFD CityWorks Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/DFD_CityWorks_Endpoint__mdt/fields/Endpoint_URI__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URI__c</fullName>
    <label>Endpoint URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/DFD_Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Comment__c.field-meta.xml
<CustomField>
    <fullName>DFD_Comment__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Comment_User__c.field-meta.xml
<CustomField>
    <fullName>DFD_Comment_User__c</fullName>
    <label>Comment User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_CW_Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>DFD_CW_Comment_ID__c</fullName>
    <description>City Works Comment Id</description>
    <label>CW Comment ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Service_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>DFD_Service_Application_Detail__c</fullName>
    <label>Service Application Detail</label>
    <referenceTo>Service_Application_Detail__c</referenceTo>
    <relationshipName>Service_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Type__c.field-meta.xml
<CustomField>
    <fullName>DFD_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DFD_Error_Messages__mdt/DFD_Error_Messages__mdt.object-meta.xml
<CustomObject>
    <label>DFD Error Message</label>
    <pluralLabel>DFD Error Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/Service_Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Created this object to capture the details of city permits</description>
    <label>Service Application Detail</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Application Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>This field is used as external ID to store the Case Number pulled from CityWorks via OIC.</description>
    <externalId>true</externalId>
    <label>Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Case_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Application_Id__c</fullName>
    <description>This field is used as external ID to store the Case Application ID pulled from CityWorks via OIC.</description>
    <externalId>true</externalId>
    <label>Case Application Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created this field to capture the status of the applications</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on customer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/fields/Synced_With_City_Works__c.field-meta.xml
<CustomField>
    <fullName>Synced_With_City_Works__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced With City Works</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DFDFW_INTOIC_AddCommentController.cls
/*
*********************************************************
Apex Class Name    : DFDFW_INTOIC_AddCommentController
Created Date       : 10/21/2024
Author             : Cloud Synapps Inc.
Description        : Class used as controller for add service comment button.
Test Class Name    : DFDFW_INTOIC_AddCommentControllerTest
*********************************************************
*/
public class DFDFW_INTOIC_AddCommentController {
  /*
  *********************************************************
  @method Name    : createCommentOnOIC
  @description    : used to create service comment on application
  @param          : commentString
  @param          : applicationId
  @param          : userId
  @return         :  String
  ********************************************************
  */
  @AuraEnabled
  public static String createCommentOnOIC(
    String commentString,
    String applicationId,
    String userId
  ) {
    try {
      List<Service_Application_Detail__c> appList = [
        SELECT Id, Case_Application_Id__c
        FROM Service_Application_Detail__c
        WHERE Id = :applicationId
        LIMIT 1
      ];
      DFD_CityWorks_Endpoint__mdt mdt = DFD_CityWorks_Endpoint__mdt.getInstance(
        'ServiceComments'
      );
      String endpoint =
        'callout:DFDFW_OIC_Endpoint' +
        mdt.Endpoint_URI__c +
        appList[0].Case_Application_Id__c;

      String accessToken = DFDFW_AUTH0_ManageUserTokenCtrl.getUserAccessToken(
        userId
      );
        
      String commentBody = '{"CommentText": "' + commentString + '"}';
      Map<String, String> headerMap = new Map<String, String>{
        'X-Access-Token' => accessToken,
        'Content-Type' => 'application/json'
      };
      String response = DFDFW_INTGEN_CallOutController.callout(
        endpoint,
        mdt.Method__c,
        true,
        commentBody,
        true,
        headerMap
      );
      Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeuntyped(
        response
      );
      if (responseMap.containsKey('Message')) {
        DFD_Comment__c scom = new DFD_Comment__c();
        scom.DFD_Comment__c = commentString;
        scom.DFD_Service_Application_Detail__c = applicationId;
        scom.DFD_CW_Comment_ID__c = Integer.valueOf(
          responseMap.get('CommentId')
        );
        scom.DFD_Comment_User__c = 'Applicant';
        scom.DFD_Type__c = 'External';
        insert scom;
      }

      return response;
    } catch (Exception e) {
      new DFDFW_LOG_AllException().Module('Service comment controller').Log(e);
      return null;
    }
  }

  /*
    *********************************************************
    @method Name    : getErrorMessageFromMetadata
    @description    : used to get error message from custom metadata
    @param          : component
    @return         : String
    ********************************************************
    */
  @AuraEnabled
  public static String getErrorMessageFromMetadata(String component) {
    String errorString;
    try {
      DFD_Error_Messages__mdt mdt = DFD_Error_Messages__mdt.getInstance(
        component
      );
      errorString = mdt.Error_Message__c;
    } catch (Exception e) {
      new DFDFW_LOG_AllException().Module('My Application controller').Log(e);
    }
    return errorString;
  }
    
    @AuraEnabled
    public static Boolean checkApplicationStatus(String recordId) {
        Boolean showButton = false;
        try {
            List<Service_Application_Detail__c> sa = [SELECT Id, Status__c, Synced_With_City_Works__c, Case_Application_Id__c, Application_Number__c FROM Service_Application_Detail__c WHERE Id =: recordId];
            if(!sa.isEmpty() && sa[0].Status__c != 'Draft' && sa[0].Case_Application_Id__c != null && sa[0].Application_Number__c != null) {
                showButton = true;
            } else {
                showButton = false;
            }
        } catch (Exception e) {
            new DFDFW_LOG_AllException().Module('My Application controller').Log(e);
        }
        return showButton;
    }
}