force-app/main/default/objects/DFD_CityWorks_Endpoint__mdt/DFD_CityWorks_Endpoint__mdt.object-meta.xml
<CustomObject>
    <label>DFD CityWorks Endpoint</label>
    <pluralLabel>DFD CityWorks Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/DFD_CityWorks_Endpoint__mdt/fields/Endpoint_URI__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URI__c</fullName>
    <label>Endpoint URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/DFD_Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Comment__c.field-meta.xml
<CustomField>
    <fullName>DFD_Comment__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Comment_User__c.field-meta.xml
<CustomField>
    <fullName>DFD_Comment_User__c</fullName>
    <label>Comment User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_CW_Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>DFD_CW_Comment_ID__c</fullName>
    <description>City Works Comment Id</description>
    <label>CW Comment ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Service_Application_Detail__c.field-meta.xml
<CustomField>
    <fullName>DFD_Service_Application_Detail__c</fullName>
    <label>Service Application Detail</label>
    <referenceTo>Service_Application_Detail__c</referenceTo>
    <relationshipName>Service_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DFD_Comment__c/fields/DFD_Type__c.field-meta.xml
<CustomField>
    <fullName>DFD_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Application_Detail__c/Service_Application_Detail__c.object-meta.xml
<CustomObject>
    <description>Created this object to capture the details of city permits</description>
    <label>Service Application Detail</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Application Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Application_Detail__c/fields/Case_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Application_Id__c</fullName>
    <description>This field is used as external ID to store the Case Application ID pulled from CityWorks via OIC.</description>
    <externalId>true</externalId>
    <label>Case Application Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DFDFW_INTOIC_GetCommentsController.cls
/*
*********************************************************
Apex Class Name    : DFDFW_INTOIC_GetCommentsController
Created Date       : 11/08/2024
Author             : Cloud Synapps Inc.
Description        : Class used as controller for get Comments from City Works.
Test Class Name    : DFDFW_INTOIC_GetCommentsControllerTest
*********************************************************
*/
public with sharing class DFDFW_INTOIC_GetCommentsController {
  /*
  *********************************************************
  @method Name    : getComment
  @description    : used to get table configurations
  @param          : applicationId
  @param          : userId
  @return         : List<DFD_Comment__c>
  ********************************************************
  */
  @AuraEnabled
  public static List<DFD_Comment__c> getComment(Id applicationId, Id userId) {
    try {
      List<Service_Application_Detail__c> appList = [
        SELECT Id, Case_Application_Id__c
        FROM Service_Application_Detail__c
        WHERE Id = :applicationId
        LIMIT 1
      ];

      List<DFD_Comment__c> newComments = new List<DFD_Comment__c>();
      DFD_CityWorks_Endpoint__mdt mdt = DFD_CityWorks_Endpoint__mdt.getInstance(
        'GetPermitCommets'
      );
      String endpoint =
        'callout:DFDFW_OIC_Endpoint' +
        mdt.Endpoint_URI__c +
        appList[0].Case_Application_Id__c;

      String accessToken = DFDFW_AUTH0_ManageUserTokenCtrl.getUserAccessToken(
        userId
      );
      UUID randomUUID = UUID.randomUUID();

      Map<String, String> headerMap = new Map<String, String>{
        'X-Access-Token' => accessToken,
        'X-Request-Id' => randomUUID.toString()
      };
      String response = DFDFW_INTGEN_CallOutController.callout(
        endpoint,
        mdt.Method__c,
        false,
        null,
        true,
        headerMap
      );

      if (response != null && response != '') {
        List<Integer> commentNumberList = new List<Integer>();
        DFDFW_INTOIC_GetCommentsWrapper responseWrapper = (DFDFW_INTOIC_GetCommentsWrapper) JSON.deserialize(
          response,
          DFDFW_INTOIC_GetCommentsWrapper.class
        );
        Map<Integer, DFDFW_INTOIC_GetCommentsWrapper.CaseComments> caseNumberToCaseComment = new Map<Integer, DFDFW_INTOIC_GetCommentsWrapper.CaseComments>();
        for (
          DFDFW_INTOIC_GetCommentsWrapper.CaseComments commentObj : responseWrapper.CaseComments
        ) {
          caseNumberToCaseComment.put(commentObj.CommentId, commentObj);
        }
        if (!caseNumberToCaseComment.isEmpty()) {
          List<DFD_Comment__c> oldComment = [
            SELECT
              Id,
              Name,
              DFD_Service_Application_Detail__c,
              DFD_Comment__c,
              DFD_Type__c,
              DFD_Comment_User__c,
              DFD_CW_Comment_ID__c
            FROM DFD_Comment__c
            WHERE
              DFD_Service_Application_Detail__c = :applicationId
              AND DFD_CW_Comment_ID__c IN :caseNumberToCaseComment.keySet()
          ];
          if (!oldComment.isEmpty()) {
            for (DFD_Comment__c comment : oldComment) {
              if (
                caseNumberToCaseComment.containsKey(
                  Integer.ValueOf(comment.DFD_CW_Comment_ID__c)
                )
              ) {
                caseNumberToCaseComment.remove(
                  Integer.ValueOf(comment.DFD_CW_Comment_ID__c)
                );
              }
            }
          }
          if (!caseNumberToCaseComment.isEmpty()) {
            for (Integer key : caseNumberToCaseComment.keySet()) {
              DFD_Comment__c comment = new DFD_Comment__c();
              DFDFW_INTOIC_GetCommentsWrapper.CaseComments caseComment = caseNumberToCaseComment.get(
                key
              );
              comment.DFD_Service_Application_Detail__c = applicationId;
              comment.DFD_Comment__c = caseComment.Comments;
              comment.DFD_CW_Comment_ID__c = caseComment.CommentId;
              if (caseComment.AuthorName == 'Applicant') {
                comment.DFD_Type__c = 'External';
              } else {
                comment.DFD_Type__c = 'Internal';
              }
              comment.DFD_Comment_User__c = caseComment.AuthorName;
              newComments.add(comment);
            }
          }

          if (!newComments.isEmpty()) {
            insert newComments;
          }
        }
      }
      return newComments;
    } catch (Exception e) {
      new DFDFW_LOG_AllException().Module('Get all comments controller').Log(e);
      return null;
    }
  }
}