force-app/main/default/objects/Budget_Table_Field__mdt/Budget_Table_Field__mdt.object-meta.xml
<CustomObject>
    <label>Budget Table Field</label>
    <pluralLabel>Budget Table Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Budget_Table_Field__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>&quot;Salaries&quot;</defaultValue>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>City of St. Louis CDBG</fullName>
            </value>
            <value>
                <fullName>Consultant and Contract Service</fullName>
            </value>
            <value>
                <fullName>Corporate Contributions</fullName>
            </value>
            <value>
                <fullName>Endowments</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Fee Revenue</fullName>
            </value>
            <value>
                <fullName>Fundraiser/Special Events</fullName>
            </value>
            <value>
                <fullName>In-Kind Expenses</fullName>
            </value>
            <value>
                <fullName>In-Kind Income</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Interest Income</fullName>
            </value>
            <value>
                <fullName>Investment Income</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Office Supplies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Federal Grants</fullName>
            </value>
            <value>
                <fullName>Payroll Taxes and Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Personnel: Salaries and Wages</fullName>
            </value>
            <value>
                <fullName>Personnel Costs</fullName>
            </value>
            <value>
                <fullName>Postage</fullName>
            </value>
            <value>
                <fullName>Printing and Copying</fullName>
            </value>
            <value>
                <fullName>Rent/Lease/Mortgage</fullName>
            </value>
            <value>
                <fullName>State Grant</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
            <value>
                <fullName>General Requirements</fullName>
            </value>
            <value>
                <fullName>Existing Conditions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Table_Field__mdt/fields/Column_Style__c.field-meta.xml
<CustomField>
    <fullName>Column_Style__c</fullName>
    <label>Column Style</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_Table_Field__mdt/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <label>Field API</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_Table_Field__mdt/fields/Rollup_Total__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Total__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rollup Total</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Table_Field__mdt/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>&quot;Default&quot;</defaultValue>
    <label>Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Match</fullName>
            </value>
            <value>
                <fullName>Not Match</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Expense Revised</fullName>
            </value>
            <value>
                <fullName>Revenue Revised</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Development Revised</fullName>
            </value>
            <value>
                <fullName>Construction Revised</fullName>
            </value>
            <value>
                <fullName>Egrams</fullName>
            </value>
            <value>
                <fullName>Expense (CDA)</fullName>
            </value>
            <value>
                <fullName>Expense (CDA) Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OperatingBudgetTablesControllerTest.cls
@istest
public with sharing class OperatingBudgetTablesControllerTest {

    @istest
    private static void test() {
        List<String> categories = new List<String>();
        string template = '';
        for( Budget_Table_Field__mdt fieldMetadata : [
            SELECT 
                Category__c,
                Template__c,
                Field_API__c,
                Rollup_Total__c,
                Required__c,
                Label,
                Column_Style__c,
                Order__c
            FROM Budget_Table_Field__mdt
            WHERE Active__c = true
            ORDER BY Category__c, Order__c
        ]) {
            categories.add( fieldMetadata.Category__c );
            template = fieldMetadata.Template__c;
        }
        Test.startTest();
        OperatingBudgetTablesController.GetData( template, categories); 
        Test.stopTest();
    }
}